apiVersion: v2
name: frontend
description: A Helm chart for Frontend microservice
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: DevOps Team
    email: devops@learningplatform.com
