apiVersion: v2
name: user-service
description: A Helm chart for User Service microservice
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: DevOps Team
    email: devops@learningplatform.com
